#!/bin/zsh
set -eu
cd "${0:A:h}"
export DEVELOPER_DIR="${COMBO_DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
./build.sh
SDK="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="$(uname -m)-apple-macosx26.0"
APP="$(xcodebuild -project Combo.xcodeproj -scheme Combo -configuration Debug -destination "platform=macOS,arch=$(uname -m)" -showBuildSettings -json | python3 -c 'import json,sys; s=json.load(sys.stdin)[0]["buildSettings"]; print(s["TARGET_BUILD_DIR"] + "/" + s["FULL_PRODUCT_NAME"])')"
OUT="$PWD/build/checks"
mkdir -p "$OUT"
xcrun swiftc -sdk "$SDK" -target "$TARGET" Combo/App/Localization.swift Combo/App/State.swift Tests/main.swift -o "$OUT/state-check"
"$OUT/state-check"
CHECK_APP="$OUT/LocalizationCheck.app"
mkdir -p "$CHECK_APP/Contents/MacOS" "$CHECK_APP/Contents/Resources"
cp -R "$APP/Contents/Resources/en.lproj" "$APP/Contents/Resources/zh-Hans.lproj" "$CHECK_APP/Contents/Resources/"
cat > "$CHECK_APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>local.combo.localization-check</string><key>CFBundleExecutable</key><string>LocalizationCheck</string></dict></plist>
PLIST
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Tests/LocalizationCheck.swift -o "$CHECK_APP/Contents/MacOS/LocalizationCheck"
"$CHECK_APP/Contents/MacOS/LocalizationCheck"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Combo/App/State.swift Combo/Rendering/IconTransition.swift Combo/Rendering/WiFiIcon.swift Combo/Rendering/IconRenderer.swift Combo/Rendering/ComboIcon.swift Tests/IconTransitionCheck.swift -o "$OUT/icon-transition-check"
"$OUT/icon-transition-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Combo/Network/WiFiControl.swift Tests/WiFiControlCheck.swift -o "$OUT/wifi-control-check"
"$OUT/wifi-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Onboarding/OnboardingState.swift Tests/OnboardingCheck.swift -o "$OUT/onboarding-check"
"$OUT/onboarding-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Network/HotspotControl.swift Tests/HotspotControlCheck.swift -o "$OUT/hotspot-control-check"
"$OUT/hotspot-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 Combo/App/Localization.swift Combo/App/State.swift Combo/Battery/ChargeControl.swift Tests/ChargeControlCheck.swift -o "$OUT/charge-control-check"
"$OUT/charge-control-check" "$APP/Contents/Helpers/ComboChargeHelper"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Battery/EnergyApps.swift Tests/EnergyAppsCheck.swift -o "$OUT/energy-apps-check"
"$OUT/energy-apps-check"
xcrun clang -isysroot "$SDK" -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror -framework Foundation Tests/MediaPlaybackHelperCheck.m -o "$OUT/media-playback-helper-check"
"$OUT/media-playback-helper-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Audio/MediaPlayback.swift Tests/MediaPlaybackCheck.swift -o "$OUT/media-playback-check"
"$OUT/media-playback-check"
codesign --verify --deep --strict "$APP"
zsh Tests/check-brand.sh "$APP"
printf 'Verified: %s\n' "$APP"
