#!/bin/zsh
set -eu
cd "${0:A:h}"
export DEVELOPER_DIR="${COMBO_DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
./build.sh
SDK="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="$(uname -m)-apple-macosx26.0"
APP="$(xcodebuild -project Combo.xcodeproj -scheme Combo -configuration Debug -destination "platform=macOS,arch=$(uname -m)" -showBuildSettings -json | python3 -c 'import json,sys; s=json.load(sys.stdin)[0]["buildSettings"]; print(s["TARGET_BUILD_DIR"] + "/" + s["FULL_PRODUCT_NAME"])')"
OUT="$PWD/build/checks"
mkdir -p "$OUT"
xcrun swiftc -sdk "$SDK" -target "$TARGET" Combo/State.swift Tests/main.swift -o "$OUT/state-check"
"$OUT/state-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/State.swift Combo/Icon.swift Tests/IconTransitionCheck.swift -o "$OUT/icon-transition-check"
"$OUT/icon-transition-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/WiFiControl.swift Tests/WiFiControlCheck.swift -o "$OUT/wifi-control-check"
"$OUT/wifi-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/OnboardingState.swift Tests/OnboardingCheck.swift -o "$OUT/onboarding-check"
"$OUT/onboarding-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/HotspotControl.swift Tests/HotspotControlCheck.swift -o "$OUT/hotspot-control-check"
"$OUT/hotspot-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 Combo/State.swift Combo/ChargeControl.swift Tests/ChargeControlCheck.swift -o "$OUT/charge-control-check"
"$OUT/charge-control-check" "$APP/Contents/Helpers/ComboChargeHelper"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/EnergyApps.swift Tests/EnergyAppsCheck.swift -o "$OUT/energy-apps-check"
"$OUT/energy-apps-check"
xcrun clang -isysroot "$SDK" -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror -framework Foundation Tests/MediaPlaybackHelperCheck.m -o "$OUT/media-playback-helper-check"
"$OUT/media-playback-helper-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/MediaPlayback.swift Tests/MediaPlaybackCheck.swift -o "$OUT/media-playback-check"
"$OUT/media-playback-check"
codesign --verify --deep --strict "$APP"
zsh Tests/check-brand.sh "$APP"
printf 'Verified: %s\n' "$APP"
