#!/bin/zsh
set -eu
cd "${0:A:h}"
export DEVELOPER_DIR="${COMBO_DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
./build.sh "$@"
python3 Tests/PanelLocalizationCheck.py
SDK="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="$(uname -m)-apple-macosx26.0"
APP="$(xcodebuild -project Combo.xcodeproj -scheme Combo -configuration Debug -destination "platform=macOS,arch=$(uname -m)" -showBuildSettings -json "$@" | python3 -c 'import json,sys; s=json.load(sys.stdin)[0]["buildSettings"]; print(s["TARGET_BUILD_DIR"] + "/" + s["FULL_PRODUCT_NAME"])')"
OUT="$PWD/build/checks"
mkdir -p "$OUT"
PRODUCTS="${APP:h}"
export DYLD_FRAMEWORK_PATH="$APP/Contents/Frameworks"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/PanelMotionCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/panel-motion-check"
"$OUT/panel-motion-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/PanelDismissCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/panel-dismiss-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/PanelDesignCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/panel-design-check"
"$OUT/panel-design-check"
"$OUT/panel-dismiss-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/DetailFeedbackCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/detail-feedback-check"
"$OUT/detail-feedback-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/SettingsPreferencesCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/settings-preferences-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -D DEBUG -parse-as-library -F "$PRODUCTS" -framework Sparkle Combo/App/AppUpdater.swift Tests/AppUpdaterCheck.swift -o "$OUT/app-updater-check"
"$OUT/app-updater-check"
"$OUT/settings-preferences-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/MediaBarsCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$OUT/media-bars-check"
"$OUT/media-bars-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" Combo/App/Localization.swift Combo/App/State.swift Combo/Audio/OutputDevice.swift Tests/main.swift -o "$OUT/state-check"
"$OUT/state-check"
CHECK_APP="$OUT/LocalizationCheck.app"
mkdir -p "$CHECK_APP/Contents/MacOS" "$CHECK_APP/Contents/Resources"
cp -R "$APP/Contents/Resources/en.lproj" "$APP/Contents/Resources/zh-Hans.lproj" "$CHECK_APP/Contents/Resources/"
cat > "$CHECK_APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>local.combo.localization-check</string><key>CFBundleExecutable</key><string>LocalizationCheck</string></dict></plist>
PLIST
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Tests/LocalizationCheck.swift -o "$CHECK_APP/Contents/MacOS/LocalizationCheck"
"$CHECK_APP/Contents/MacOS/LocalizationCheck"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Combo/App/State.swift Combo/Audio/OutputDevice.swift Combo/Rendering/IconTransition.swift Combo/Rendering/WiFiIcon.swift Combo/Rendering/IconRenderer.swift Combo/Rendering/ComboIcon.swift Tests/IconTransitionCheck.swift -o "$OUT/icon-transition-check"
"$OUT/icon-transition-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Combo/Network/WiFiControl.swift Tests/WiFiControlCheck.swift -o "$OUT/wifi-control-check"
"$OUT/wifi-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Onboarding/OnboardingState.swift Tests/OnboardingCheck.swift -o "$OUT/onboarding-check"
"$OUT/onboarding-check"
GUIDE_CHECK_APP="$OUT/OnboardingDesignCheck.app"
mkdir -p "$GUIDE_CHECK_APP/Contents/MacOS" "$GUIDE_CHECK_APP/Contents/Resources"
cp -R "$APP/Contents/Resources/en.lproj" "$APP/Contents/Resources/zh-Hans.lproj" "$APP/Contents/Resources/Assets.car" "$APP/Contents/Resources/AppIcon.icns" "$GUIDE_CHECK_APP/Contents/Resources/"
cat > "$GUIDE_CHECK_APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>local.combo.onboarding-design-check</string><key>CFBundleExecutable</key><string>OnboardingDesignCheck</string></dict></plist>
PLIST
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library -I "$PRODUCTS" -F "$PRODUCTS" Tests/OnboardingDesignCheck.swift "$APP/Contents/MacOS/Combo.debug.dylib" -Xlinker -rpath -Xlinker "$APP/Contents/MacOS" -o "$GUIDE_CHECK_APP/Contents/MacOS/OnboardingDesignCheck"
"$GUIDE_CHECK_APP/Contents/MacOS/OnboardingDesignCheck"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Network/HotspotControl.swift Tests/HotspotControlCheck.swift -o "$OUT/hotspot-control-check"
"$OUT/hotspot-control-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 Combo/App/Localization.swift Combo/App/State.swift Combo/Audio/OutputDevice.swift Combo/Battery/ChargeControl.swift Tests/ChargeControlCheck.swift -o "$OUT/charge-control-check"
"$OUT/charge-control-check" "$APP/Contents/Helpers/ComboChargeHelper"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Battery/EnergyApps.swift Tests/EnergyAppsCheck.swift -o "$OUT/energy-apps-check"
"$OUT/energy-apps-check"
xcrun clang -isysroot "$SDK" -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror -framework Foundation Tests/MediaPlaybackHelperCheck.m -o "$OUT/media-playback-helper-check"
"$OUT/media-playback-helper-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Audio/MediaPlayback.swift Tests/MediaPlaybackCheck.swift -o "$OUT/media-playback-check"
"$OUT/media-playback-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Audio/OutputDevice.swift Combo/Audio/AirPlayRoute.swift Combo/Audio/AirPlayDiscovery.swift Tests/OutputDeviceCheck.swift -o "$OUT/output-device-check"
"$OUT/output-device-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Audio/OutputDevice.swift Combo/Audio/AirPlayRoute.swift Tests/AirPlayRouteCheck.swift -o "$OUT/airplay-route-check"
"$OUT/airplay-route-check"
xcrun clang -isysroot "$SDK" -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror -framework Foundation -framework CoreAudio -framework IOBluetooth Tests/AirPlayHelperCheck.m -o "$OUT/airplay-helper-check"
"$OUT/airplay-helper-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/Audio/OutputDevice.swift Combo/Audio/AirPlayDiscovery.swift Tests/AirPlayDiscoveryCheck.swift -o "$OUT/airplay-discovery-check"
"$OUT/airplay-discovery-check"
xcrun swiftc -sdk "$SDK" -target "$TARGET" -swift-version 5 -parse-as-library Combo/App/Localization.swift Combo/Audio/AudioVolume.swift Combo/Audio/AirPodsControl.swift Tests/AirPodsCheck.swift -o "$OUT/airpods-check"
"$OUT/airpods-check"
codesign --verify --deep --strict "$APP"
zsh Tests/check-brand.sh "$APP"
printf 'Verified: %s\n' "$APP"
