import Foundation
assert(volumeDots(nil) == nil)
assert(volumeDots(0) == 0)
assert(volumeDots(0.01) == 1)
assert(volumeDots(0.25) == 1)
assert(volumeDots(0.26) == 2)
assert(volumeDots(1) == 4)
assert(volumeDots(-0.1) == nil)
assert(volumeDots(.nan) == nil)
assert(bottomState(muted: true, adjusting: true, playing: true, animate: true) == .muted)
assert(bottomState(muted: false, adjusting: true, playing: true, animate: true) == .volume)
assert(bottomState(muted: false, adjusting: false, playing: true, animate: true) == .playing)
assert(bottomState(muted: false, adjusting: false, playing: true, animate: false) == .volume)
print("PASS: volume boundaries and display precedence")
assert(Scene.allCases.count == 13) // 12 reference states plus live data.
assert(Snapshot.demo(.music).symbol.isEmpty)
assert(Snapshot.demo(.adjusting).volume == 0.75)
assert(Snapshot.demo(.output).headphones)
assert(Snapshot.demo(.date).day == "22")
assert(Snapshot.demo(.reduced).reducedMotion)
print("PASS: reference scene coverage")
assert(resolveTransport(pathAvailable: false, interfaces: ["wifi"]) == "offline")
assert(resolveTransport(pathAvailable: true, interfaces: ["wifi", "ethernet"]) == "unknown")
assert(resolveTransport(pathAvailable: true, interfaces: ["wifi", "wifi"]) == "wifi")
assert(resolveTransport(pathAvailable: true, interfaces: ["tunnel"]) == "unknown")
assert(resolveTransport(pathAvailable: nil, interfaces: []) == "pending")
assert(volumeHintActive(changedAt: 10, now: 11.99))
assert(!volumeHintActive(changedAt: 10, now: 12))
assert(!volumeHintActive(changedAt: nil, now: 11))
print("PASS: conservative routes and volume hint expiry")
